### ISSUE TITLE
Now cannot receive push when app is on foreground

### ISSUE THREAD

**Issue by vanphuc3112** [Pushwoosh/pushwoosh-flutter#11]
Last time we have error that push cannot received when app go to background. It is fixed.
But now problem is that when app is opening and send push, we cannot receive push, error log is:
`E/Pushwoosh(31024): Exception occurred
E/Pushwoosh(31024): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Firebase-PushFcmIntentService
E/Pushwoosh(31024): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/Pushwoosh(31024): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
E/Pushwoosh(31024): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/Pushwoosh(31024): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:174)
E/Pushwoosh(31024): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:144)
E/Pushwoosh(31024): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:226)
E/Pushwoosh(31024): 	at com.pushwoosh.plugin.PushwooshPlugin$StreamHandler.sendEvent(PushwooshPlugin.java:249)
E/Pushwoosh(31024): 	at com.pushwoosh.plugin.PushwooshPlugin$StreamHandler.access$100(PushwooshPlugin.java:243)
E/Pushwoosh(31024): 	at com.pushwoosh.plugin.PushwooshPlugin.onMessageReceived(PushwooshPlugin.java:56)
E/Pushwoosh(31024): 	at com.pushwoosh.plugin.PushwooshNotificationServiceExtension.onMessageReceived(PushwooshNotificationServiceExtension.java:36)
E/Pushwoosh(31024): 	at com.pushwoosh.notification.NotificationServiceExtension.a(Unknown Source)
E/Pushwoosh(31024): 	at com.pushwoosh.notification.NotificationServiceExtension.handleMessage(Unknown Source)
E/Pushwoosh(31024): 	at com.pushwoosh.PushwooshFcmHelper.onMessageReceived(Unknown Source)
E/Pushwoosh(31024): 	at com.pushwoosh.PushFcmIntentService.onMessageReceived(Unknown Source)
E/Pushwoosh(31024): 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
E/Pushwoosh(31024): 	at com.google.firebase.iid.zzb.run(Unknown Source)
E/Pushwoosh(31024): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/Pushwoosh(31024): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/Pushwoosh(31024): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
E/Pushwoosh(31024): 	at java.lang.Thread.run(Thread.java:762)`

Please help me check this problem.
Thank you

**Comment by wfhm** [comment]
@vanphuc3112,

Checking it.

**Comment by rinlv** [comment]
@wfhm This bug maybe happens cause of version of flutter. Currently, the stable version is v1.7.8+hotfix.3

**Comment by wfhm** [comment]
@rinlv,

Thank you for the suggestion, will check it with 1.7.8+hotfix.3 version as well.

**Comment by wfhm** [comment]
@vanphuc3112 @rinlv,

Fixed with the latest release.
