### ISSUE TITLE
registerForPushNotifications cannot retrieve token

### ISSUE THREAD

**Issue by Tregan** [Pushwoosh/pushwoosh-flutter#13]
Hello,

We started implementing Pushwoosh in our Flutter application, but when we call registerForPushNotifications, we get an exception. 

> E/Pushwoosh( 1077): [PushRegistrarFCM] FCM registration error: Failed to retrieve token. Is firebase configured correctly?
> I/flutter ( 1077): PlatformException(RegisterForPushNotificationsException, , com.pushwoosh.exception.RegisterForPushNotificationsException:
> I/flutter ( 1077): 	at com.pushwoosh.notification.h.a(Unknown Source:13)
> I/flutter ( 1077): 	at com.pushwoosh.notification.j.onReceive(Unknown Source:4)
> I/flutter ( 1077): 	at com.pushwoosh.internal.event.EventBus.b(Unknown Source:23)
> I/flutter ( 1077): 	at com.pushwoosh.internal.event.EventBus.a(Unknown Source:0)
> I/flutter ( 1077): 	at com.pushwoosh.internal.event.c.run(Unknown Source:4)
> I/flutter ( 1077): 	at android.os.Handler.handleCallback(Handler.java:789)
> I/flutter ( 1077): 	at android.os.Handler.dispatchMessage(Handler.java:98)
> I/flutter ( 1077): 	at android.os.Looper.loop(Looper.java:164)

For the implementation I followed the guide and placed the google-services.json file in the android/app folder (Is that really required? What would be a good solution for flavor-dependant package names? e.g. com.company.app & com.company.app.dev). Firebase is configured correctly, because our Unity app can receive push notifications just fine. Using latest stable version of Flutter, 1.7.8+hotfix.3.

Yours,
Bas

**Comment by wfhm** [comment]
@Tregan,

Checking it.

**Comment by wfhm** [comment]
@Tregan Got it reproduced. I will come back to you once I have any news on a solution.

**Comment by wfhm** [comment]
@Tregan turned out I messed up with platform initialization, and everything works fine with the latest plugin version. Could you please check that you have `classpath 'com.google.gms:google-services:4.0.1'` dependency in your build.gradle?

Also, please double-check that parameters you pass to `Pushwoosh.initialize()` are correct.

**Comment by Tregan** [comment]
Got it working, thanks! :) You might want to update the flutter integration guide, because the following is missing in the integration guide:

- Add `classpath 'com.google.gms:google-services:4.0.1'` to android\build.gradle dependencies
- Add `apply plugin: 'com.google.gms.google-services'` to android\app\build.gradle

The 'apply plugin' requires the google-services.json file to be present, and if you're working with build types & flavors, like me, check out https://developers.google.com/android/guides/google-services-plugin#adding_the_json_file to see how you can add multiple google-services.json files to your project.

**Comment by wfhm** [comment]
@Tregan,

Absolutely, I'm already on it:) Thanks for pointing it out!

As for flavor-dependant package names, you can just add several IDs to your project in Firebase Console and get updated google-services.json file from there.

**Comment by Tregan** [comment]
@wfhm Yep I now have 2 Firebase projects: 1 for production and 1 for development. Development contains 2 apps (com.company.app.dev and com.company.app.qa). This is because I have 2 Pushwoosh apps to keep production notifications separate from development ones.

So my android\app\src folder has 3 folders for the flavors: dev, qa, prod. dev and qa both contain the same google-services.json file from the development Firebase project, and prod contains the production Firebase project file.
