### ISSUE TITLE
Notification is replaced when new notification come

### ISSUE THREAD

**Issue by wongpiwat** [Pushwoosh/pushwoosh-flutter#14]
I want display multiple notifications in android. When I send a new push notification, it replaces the old one in the android notification bar. I don't know how to resolve it?

**Comment by wfhm** [comment]
@wongpiwat,

You should enable MultiNotificationMode:


    PushwooshNotificationSettings.setMultiNotificationMode(true);

**Comment by wongpiwat** [comment]
@wfhm,
I have import 'package:pushwoosh/pushwoosh.dart' but I don't find setMultiNotificationMode function in pushwoosh.dart.

**Comment by wfhm** [comment]
@wongpiwat,

Indeed there is no binding for this method in flutter plugin yet. Will be added with the next release.

**Comment by wfhm** [comment]
@wongpiwat,

**setMultiNotificationMode()** function is added with the latest release.
