### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by juliocbcotta** [Pushwoosh/pushwoosh-flutter#16]
Hey, how about to migrate to AndroidX libraries?

**Comment by wfhm** [comment]
Hello @BugsBunnyBR,

I have passed your request to our SDK Team in order to check such a possibility.

Please stay tuned!

**Comment by wfhm** [comment]
@BugsBunnyBR,

This will not be done in the nearest future. Flutter plugin is based on our native SDK, as well as plugins for other frameworks, such as Cordova, React Native, Adobe Air, Unity etc. Some of these frameworks still do not support androidx libs, so we have to stick with Android Support so far. However, you can use AndroidX libs in your Flutter project - our plugin perfectly works with Jetifier.

**Comment by juliocbcotta** [comment]
Just because it will not be done in the nearest future it does not mean it is solved or is an invalid issue. How about to keep it open while the migration is not done?

**Comment by JZ-at-TP** [comment]
@BugsBunnyBR - This isn't ideal and can cause other issue, but it does work:

In `andorid/build.gradle`:


    ext {
        compileSdkVersion = 28
    }

    rootProject.buildDir = '../build'
    subprojects {
        project.buildDir = "${rootProject.buildDir}/${project.name}"

        // force all sub-projects to use compileSdkVersion defined in root gradle
        afterEvaluate{
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
            }
        }
    }


In `andorid/app/build.gradle`:

`compileSdkVersion rootProject.ext.compileSdkVersion`

This will force the compile version of pushwoosh (and well everything) to 28 and lets it build.

**Comment by wfhm** [comment]
@BugsBunnyBR @JZ-at-TP the plugin is finally migrated to AndroidX starting with the 2.0.0 release.
