### ISSUE TITLE
Cannot open app (app is running in background or not running) when click on notification has deeplink

### ISSUE THREAD

**Issue by nhanv** [Pushwoosh/pushwoosh-flutter#19]
I have an issues:
- I push a notification without deeplink just have data (pushwoosh message have "u" tag). My app received push notification (app is running in background or not running) then I click on notification => handle data and open app OK

But

- I push a notification with deeplink and data (pushwoosh message has "l" and "u" tags). My app received push notification (app is running in background or not running) then I click on notification => I can handle data to direct to new screen but app NOT OPEN.

Please help,

**Comment by wfhm** [comment]
Hi @nhanv,

As far as I can see, our Support Team has already responded to you in the support ticket you have created. In order to avoid confusion in correspondence, let's continue the investigation process there!
