### ISSUE TITLE
App Crashes on notification arriving

### ISSUE THREAD

**Issue by pixelgroup-israel** [Pushwoosh/pushwoosh-flutter#20]
Can anyone help with this?
This is what I get in the console.

D/AndroidRuntime( 6697): Shutting down VM
E/AndroidRuntime( 6697): FATAL EXCEPTION: main
E/AndroidRuntime( 6697): Process: com.globalbit.maariv.app, PID: 6697
E/AndroidRuntime( 6697): java.lang.RuntimeException: Unable to instantiate service com.pushwoosh.PushFcmIntentService: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushFcmIntentService" on path: DexPathList[[zip file "/data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/lib/arm64, /data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
E/AndroidRuntime( 6697): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4136)
E/AndroidRuntime( 6697): 	at android.app.ActivityThread.access$2400(ActivityThread.java:273)
E/AndroidRuntime( 6697): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2055)
E/AndroidRuntime( 6697): 	at android.os.Handler.dispatchMessage(Handler.java:112)
E/AndroidRuntime( 6697): 	at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime( 6697): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/AndroidRuntime( 6697): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6697): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/AndroidRuntime( 6697): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/AndroidRuntime( 6697): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.pushwoosh.PushFcmIntentService" on path: DexPathList[[zip file "/data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/lib/arm64, /data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
E/AndroidRuntime( 6697): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime( 6697): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 6697): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 6697): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
E/AndroidRuntime( 6697): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
E/AndroidRuntime( 6697): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4131)
E/AndroidRuntime( 6697): 	... 8 more
E/AndroidRuntime( 6697): 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/FirebaseMessagingService;
E/AndroidRuntime( 6697): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 6697): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 6697): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 6697): 		... 12 more
E/AndroidRuntime( 6697): 	Caused by: java.lang.ClassNotFoundException: com.google.firebase.messaging.FirebaseMessagingService
E/AndroidRuntime( 6697): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime( 6697): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime( 6697): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime( 6697): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 6697): 		... 15 more
E/AndroidRuntime( 6697): 	Caused by: java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.globalbit.maariv.app-ONumM5rlKgqN6kVI9Izx0Q==/base.apk!classes2.dex)
E/AndroidRuntime( 6697): 		... 15 more
E/        ( 6697): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
I/Process ( 6697): Sending signal. PID: 6697 SIG: 9
Lost connection to device.
Exited (sigterm)

**Comment by pixelgroup-israel** [comment]
Just saw that it also happens on app load without a push being sent.

**Comment by wfhm** [comment]
Hi @pixelgroup-israel,

It seems that there is a conflict between google libraries in your project.

In order to investigate this case in more details, could you please provide us with the following files?

*pubspec.yaml
*build.gradle
*reproducer .apk file

**Comment by pixelgroup-israel** [comment]
pubspec.yaml:

`
name: maariv
description: A new Flutter project.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  scoped_model: ^1.0.1
  http: ^0.12.0+2
  flutter_google_ad_manager: ^0.10.1
  flutter_widget_from_html: ^0.2.4+4
  webview_flutter: ^0.3.15+1
  marquee_widget:
    path: ./assets/custom_widgets/marquee_widget-0.8.0-custom/
  carousel_slider: ^1.3.0
  url_launcher: ^5.2.7
  firebase_core: ^0.4.2+1
  firebase_analytics: ^5.0.6
  flutter_share_me: ^0.8.0
  shared_preferences: ^0.5.4+6
  flutter_launcher_icons: "^0.7.3"
  pushwoosh: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/image_placeholder.png
    - assets/images/placeholder.gif
    - assets/images/logo.png
    - assets/images/logo_white.png
    - assets/images/menu-icon.png
    - assets/images/arrow-link.png
    - assets/images/breaking.png
    - assets/images/video.png
    - assets/images/facebook.png
    - assets/images/twitter.png
    - assets/images/whatsapp.png
    - assets/images/email.png
    - assets/images/size-icon.png
    - assets/images/share-icon.png
    - assets/images/category_arrow.png
    - assets/images/red_email.png
    - assets/images/outbrainLogo.png

  fonts:
    - family: Adom
      fonts:
        - asset: assets/fonts/Adom-Regular.ttf
          weight: 400
        - asset: assets/fonts/Adom-Medium.ttf
          weight: 500
    - family: OpenSansHebrew
      fonts:
        - asset: assets/fonts/OpenSansHebrew-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSansHebrew-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSansHebrew-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSansHebrew-ExtraBold.ttf
          weight: 900
`

build.gradle:

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.globalbit.maariv.app"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
       release {
           keyAlias keystoreProperties['keyAlias']
           keyPassword keystoreProperties['keyPassword']
           storeFile file(keystoreProperties['storeFile'])
           storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'androidx.multidex:multidex:2.0.1'
    api 'com.outbrain.obsdk:obsdk:3.7.10'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation 'com.google.firebase:firebase-iid:17.1.2'
}
`

what is reproducer .apk file?

**Comment by wfhm** [comment]
@pixelgroup-israel,

In your build.gradle you use 17.1.2 version of the **firebase-iid** library:

    implementation 'com.google.firebase:firebase-iid:17.1.2'

Pushwoosh SDK uses the **com.google.gms:google-services** plugin which requires 18.0.0 version of the **iid** lib. Please try updating it to the 18.0.0 and let us know about the results.

**Comment by wfhm** [comment]
@pixelgroup-israel

Thanks for the information provided!

Additionally, may I ask you to specify the version of Android studio you are using at the moment and provide us with the "top-level" build.gradle file?

**Comment by pixelgroup-israel** [comment]
Hi,

I'm not using Android Studio, but VSCode.

Top Level build.gradle:

`
buildscript {
    ext.kotlin_version = '1.3.0'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://dl.bintray.com/outbrainmobile/obsdk'
            credentials {
                username = "OutbrainPublishers"
                password = "********"
            }
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

subprojects {
    project.configurations.all {
	resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
	       !details.requested.name.contains('androidx')) {
		details.useVersion "1.0.1"
            }
	}
    }    
}

`

**Comment by wfhm** [comment]
@pixelgroup-israel,

In your `build.gradle` you use 17.1.2 version of the **firebase-iid** library:

    implementation 'com.google.firebase:firebase-iid:17.1.2'

Pushwoosh SDK uses the **com.google.gms:google-services** plugin which requires 18.0.0 version of the **iid** lib. Please try updating it to the 18.0.0 and let us know about the results.

**Comment by pixelgroup-israel** [comment]
Hi @wfhm ,

I have tried removing the dependency to 17.1.2, and also to explicitly require 18.0.0.
In both cases the app crashed upon receiving the push notification.

Here is the stack trace:

`
E/AndroidRuntime(23011): FATAL EXCEPTION: main
E/AndroidRuntime(23011): Process: com.globalbit.maariv.app, PID: 23011
E/AndroidRuntime(23011): java.lang.IllegalAccessError: Class com.google.firebase.iid.zzb extended by class com.google.firebase.messaging.FirebaseMessagingService is inaccessible (declaration of 'com.google.firebase.messaging.FirebaseMessagingService' appears in /data/app/com.globalbit.maariv.app-hNugyelTGbbuV_V3KGNHjA==/base.apk!classes2.dex)
E/AndroidRuntime(23011): 	at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(23011): 	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(23011): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(23011): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(23011): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(23011): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
E/AndroidRuntime(23011): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4135)
E/AndroidRuntime(23011): 	at android.app.ActivityThread.access$1600(ActivityThread.java:267)
E/AndroidRuntime(23011): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1997)
E/AndroidRuntime(23011): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(23011): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(23011): 	at android.app.ActivityThread.main(ActivityThread.java:7770)
E/AndroidRuntime(23011): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23011): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(23011): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)
I/Process (23011): Sending signal. PID: 23011 SIG: 9
Lost connection to device.
Exited (sigterm)
`

**Comment by pixelgroup-israel** [comment]
@wfhm 

Any news regarding this issue?

Thanks,
Amit

**Comment by wfhm** [comment]
@pixelgroup-israel,

No news so far. By any chance, is it possible for you to provide a reproducer APK to us so we could try it on our side? If it is, please send it via email to help@pushwoosh.com with the reference to this issue.
