### ISSUE TITLE
Cannot handle push when app in background in iOS

### ISSUE THREAD

**Issue by nhanv** [Pushwoosh/pushwoosh-flutter#24]
I'm using latest version 1.20.0. This case worked on android but not work on iOS:
1. App is running in foreground
2. Received new push
3. Open multitask and swipe to close app
4. Click on notification in Notification Tray
5. App open but I cannot receive data push in Pushwoosh.getInstance.onPushReceived to handle action.

Can you check it or guide for me how to handle push on this case.
Thank you.

**Comment by wfhm** [comment]
Hi @nhanv,

Checking it.

**Comment by wfhm** [comment]
@nhanv,

Confirmed, the issue is on our side. First, we have to fix it in native iOS SDK, then, the plugin will be updated.

**Comment by wfhm** [comment]
@nhanv,

Fixed with the latest release.
