### ISSUE TITLE
Read custom data when app is closed

### ISSUE THREAD

**Issue by matszafraniec** [Pushwoosh/pushwoosh-flutter#25]
I would like to ask if there is a possibility to receive and read custom data from push notifications if app is closed?

When the app is opened, methods: `onPushReceived`, `onPushAccepted`, `onDeepLinkOpened` works fine, and custom data can be easily read, but I can't find a way how to read that data when app is closed.

**Comment by wfhm** [comment]
@matszafraniec,

Opening a closed app via a push notification should actually trigger the onPushAccepted callback. Does it happen in your project? If not, could you please specify what plugin version is used, what OS is affected, and its version?

**Comment by matszafraniec** [comment]
@wfhm

The application opens after touching the notification, but custom data is not read in onPushAccepted method. 

I'm using latest version of Pushwoosh package and Flutter 1.22.1. I checked it on Android device with Android 9.0.

**Comment by wfhm** [comment]
@matszafraniec,

I got it reproduced - this is on our side, and it will be fixed with the next release. Meanwhile, you can use the following solution as a workaround (let's say you send `{"key": "value"}` as your custom data):

        Pushwoosh.getInstance.onPushAccepted.listen((event) {
          var message = event.pushwooshMessage;
          print(message.payload['userdata']); //returns {key: value}
          print(message.payload['u']); //returns {"key": "value"}
        });

**Comment by matszafraniec** [comment]
Thank you @wfhm

**Comment by wfhm** [comment]
@matszafraniec fixed with 2.0.0. release.

**Comment by matszafraniec** [comment]
Thank you @wfhm .
