### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by Tregan** [Pushwoosh/pushwoosh-flutter#35]
It would be great if the package could be [migrated to null safety](https://dart.dev/null-safety/migration-guide)

**Comment by mediproductions** [comment]
+1

**Comment by iamwalter** [comment]
+1

**Comment by wfhm** [comment]
@Tregan @iamwalter  @mediproductions will be done with the next release

**Comment by wfhm** [comment]
@Tregan @iamwalter @mediproductions done, the package was migrated to null safety with the 2.2.0 release.
