### ISSUE TITLE
IllegalStateException after upgrading Firebase plugins

### ISSUE THREAD

**Issue by teknofreek** [Pushwoosh/pushwoosh-flutter#37]
Exception:

E/AndroidRuntime(26479): java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: You must add "implementation 'com.google.firebase:firebase-messaging:+'" line to your app build.gradle.

Although 'firebase-messaging' implementation is already added in my build.gradle file.

Caused by: java.lang.ClassNotFoundException: com.google.firebase.iid.FirebaseInstanceId

I guess we need to upgrade firebase messaging version

**Comment by wfhm** [comment]
@transitguide 

You are using  'com.google.firebase:firebase-messaging:+' which fetches the latest version (22.0.0) - Google removed the InsanceId library from firebase-messaging module starting with this version, so we have to migrate our SDK from using old Instance IDs as push tokens to new Firebase API tokens. This might take some time, so, as a temporary workaround, you can just add the missing Instance ID library separately:

```implementation "com.google.firebase:firebase-iid:21.1.0"```

**Comment by teknofreek** [comment]
Thank you. Integration is done, but notofications are not being received, no listener is called. What could be wrong.

**Comment by wfhm** [comment]
@transitguide this is really hard to say at this point. Could it be that you have another library that adds its own FirebaseMessagingService to your app? If so, only one of the services registered in AndroidManifest.xml will work at a time, and, if the service added by the other library has higher priority - pushes will never be received by Pushwoosh SDK. May I ask you to share build.gradle files (project- and app- level) so we could check if that is the case? Also, it would be really helpful if you could share a reproducer with us - is that by any chance possible?
