### ISSUE TITLE
Android V2 embedding

### ISSUE THREAD

**Issue by matszafraniec** [Pushwoosh/pushwoosh-flutter#39]
When I try to build my project with Flutter 2.5.1 I can see this warning:

_The plugins `pushwoosh` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration._

Are you planning to fix it?

**Comment by wfhm** [comment]
@matszafraniec,

Will be done with the next plugin release.

**Comment by wfhm** [comment]
@matszafraniec plugin was migrated with the latest release.
