### ISSUE TITLE
Null safety error

### ISSUE THREAD

**Issue by mediproductions** [Pushwoosh/pushwoosh-flutter#43]
Hi,

I've just installed the new package 2.2.0.
I made a flutter clean and I can't compile.
`Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:pushwoosh

    For solutions, see https://dart.dev/go/unsound-null-safety`

In my source, the pushwooh import is underlined with this inspection report : 
`The library 'package:pushwoosh/pushwoosh.dart' is legacy, and should not be imported into a null safe library.  Try migrating the imported library.
/Users/yannick/.pub-cache/hosted/pub.dartlang.org/pushwoosh-2.2.0/lib/pushwoosh.dart
`

from the pub.dev:
`
Support sound null safety
0
/
20

0/20 points: Package does not opt in to null safety.
Package language version (indicated by the sdk constraint `>=1.19.0 <3.0.0`) is less than 2.12.
Consider migrating.`

**Comment by wfhm** [comment]
@mediproductions Checking it.

**Comment by wfhm** [comment]
@mediproductions Fixed in 2.2.1.
