### ISSUE TITLE
Future registerForPushNotifications does not complete after 30 seconds sometimes

### ISSUE THREAD

**Issue by paulononaka** [Pushwoosh/pushwoosh-flutter#50]
Hi,

Sometimes the registerForPushNotifications call does not ever complete:
`String? token = await Pushwoosh.getInstance.registerForPushNotifications()`

So I was forced to add a timeout on it myself:
`String? token = await Pushwoosh.getInstance.registerForPushNotifications().timeout(const Duration(seconds: 30));`

Although I wanted to ask you why for some cases it does not finish.

PS: 
- Project has been successfully initialized, events and everything else works fine. 
- I couldn't identify what causes it, but it works for some people and for others not.

**Comment by wfhm** [comment]
Hi @paulononaka,

Please let me pull some time to investigate it. Meanwhile, could you please let me know if you found any reliable steps to reproduce the issue? Is there any app behavior pattern that causes registration method to never complete?

**Comment by OmerTrainer** [comment]
any news regarding this issue?

**Comment by enginseer-dev** [comment]
Hello, @OmerTrainer 

Our register device API operates with a maximum response time of 6 milliseconds, under the vigilant oversight of our DevOps team.

Attempts to replicate the issue have been unsuccessful.

For further investigation, could you provide:
1. Do you have any reliable steps to reproduce the issue?
2. Platform of the devices (iOS, Android) that experience the issue.
3. Device models affected.
4. Location of the devices (country, city).
