### ISSUE TITLE
no valid aps-environment entitlement string found for application

### ISSUE THREAD

**Issue by alexlovar** [Pushwoosh/pushwoosh-flutter#54]
Hi, is using flutter 3, my Android version is running well, but the iOS version is returning an error and i can't get the registration token; in the runner capabilities is enabled "remote notification", the googleservice-info.plist is  located in the runner folder and  my runner. Entitlements have the lines:

```
 <key>aps-environment</key>
 <string>development</string>
```
the result error when try to get the token is the follow:

```
[PW] [D] -[PWNotificationManagerCompatiOS10] NotificationCenter authorization granted: 1
[PW] [E] dynamicDidFailToRegisterForRemoteNotificationsWithError] Error registering for push notifications. Error: Error Domain=NSCocoaErrorDomain Code=3000 "no valid “aps-environment” entitlement string found for application" UserInfo={NSLocalizedDescription=no valid “aps-environment” entitlement string found for application}
```

**Comment by wfhm** [comment]
@alexlovar You should add **Push Notifications** capability and not **Remote Notifications background mode**. Could you please double-check that you have **Push Notifications** enabled for your app?

Also, we do not use Firebase for iOS push notifications, so there is no need for adding the googleservice-info.plist to a project (unless you use another push service alongside with Pushwoosh).

**Comment by alexlovar** [comment]
thank you much, is correct, solved
