### ISSUE TITLE
ios badges setup gives build error - Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_PushwooshPlugin"

### ISSUE THREAD

**Issue by davidequadrelli-b** [Pushwoosh/pushwoosh-flutter#63]
I'm trying setting up the badges as described in the documentation in my Flutter project
[https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/flutter/setting-up-badges-for-flutter](https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/cross-platform-frameworks/flutter/setting-up-badges-for-flutter)

I followed all the step required but in the end I get the following error:

    Undefined symbols for architecture arm64:
    "_OBJC_CLASS_$_PushwooshPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

This is the result of flutter doctor

    [✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale it-IT)
        • Flutter version 3.10.4 on channel stable at /Users/davide.quadrelli/flutter/flutter_3
        • Upstream repository https://github.com/flutter/flutter.git
        • Framework revision 682aa387cf (2 weeks ago), 2023-06-05 18:04:56 -0500
        • Engine revision 2a3401c9bb
        • Dart version 3.0.3
        • DevTools version 2.23.1
    
    [✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
        • Android SDK at /Users/davide.quadrelli/Library/Android/sdk
        • Platform android-33, build-tools 33.0.1
        • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
        • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
        • All Android licenses accepted.
    
    [✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
        • Xcode at /Applications/Xcode.app/Contents/Developer
        • Build 14E300c
        • CocoaPods version 1.12.1
    
    [✓] Android Studio (version 2022.2)
        • Android Studio at /Applications/Android Studio.app/Contents
        • Flutter plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/9212-flutter
        • Dart plugin can be installed from:
          🔨 https://plugins.jetbrains.com/plugin/6351-dart
        • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    
    [✓] IntelliJ IDEA Community Edition (version 2022.2.3)
        • IntelliJ at /Applications/IntelliJ IDEA CE.app
        • Flutter plugin version 70.2.5
        • Dart plugin version 222.4345.14
    
    [✓] VS Code (version 1.79.2)
        • VS Code at /Applications/Visual Studio Code.app/Contents
        • Flutter extension version 3.66.0
    
    [✓] Connected device (1 available)
        • macOS (desktop) • macos • darwin-arm64 • macOS 13.4 22F66 darwin-arm64
    
    [✓] Network resources
        • All expected network resources are available.

The flutter dependencies in `pubspec.yaml` are

    pushwoosh: '2.2.13'
    pushwoosh_inbox: '2.2.13' 

These are the changes made in `Podfile`:

    target 'NotificationService' do
      use_frameworks!
      # use_modular_headers!
      pod 'PushwooshXCFramework', '=6.4.12'
    end
   
Do you have any idea of what's the problem?

**Comment by akidisdev** [comment]
@davidequadrelli-b Hi! We have reproduced the issue on our side. Will be fixed shortly.

**Comment by wfhm** [comment]
@davidequadrelli-b Does your project require adding `use_frameworks!` to your targets in Podfile? If not, then you can simply remove that line from your Podfile, run `pod install --repo-update` in /ios directory and it should fix the issue.

**Comment by davidequadrelli-b** [comment]
@wfhm Yes, our project require the `use_frameworks!` because we have `GSPlayer` as a native ios dependency and it requires to be compiled as a framework

**Comment by wfhm** [comment]
@davidequadrelli-b got it. We are migrating the plugin to xcframework right now, and the new version will be released shortly. However the issue you reported still persists after migration, so we are still looking into it.

**Comment by wfhm** [comment]
@davidequadrelli-b Fixed in 2.2.14. Please note that package name had changed from `pushwoosh` to `pushwoosh_flutter` starting with this version, so you'll have to update your pubspec and imports accordingly. We will update public docs shortly, meanwhile you can refer to the changelog:
https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.14

**Comment by davidequadrelli-b** [comment]
@wfhm Now with the new `pushwoosh_flutter` everything is working, thank you for the support
