### ISSUE TITLE
iOS Provisional Push

### ISSUE THREAD

**Issue by lukasbachlechner** [Pushwoosh/pushwoosh-flutter#64]
Hey, 

any plans to support provisional push for iOS devices? According to the native iOS docs, this is just a config value before initialising, but there doesn't seem to be a way for doing that with the Flutter plugin.

**Comment by Ankononenko** [comment]
Hello, @lukasbachlechner 

Provisional Push support is already present in our native iOS framework. We understand the need to extend this feature to our Flutter plugin as well. We appreciate your patience and will have this addressed soon.

**Comment by lukasbachlechner** [comment]
@finchren Perfect, thank you :)

**Comment by wfhm** [comment]
@lukasbachlechner Added in 2.2.14. To enable it, call `requestProvisionalAuthOptions()` method before calling `registerForPushNotifications()`.

Please note that package name had changed from `pushwoosh` to `pushwoosh_flutter` starting with this version, so you'll have to update your pubspec and imports accordingly. We will update public docs shortly, meanwhile you can refer to the changelog:
https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.14
