### ISSUE TITLE
Error when flutter app received push notification

### ISSUE THREAD

**Issue by rinlv** [Pushwoosh/pushwoosh-flutter#7]
I got this error when flutter app received a notification and notification didn't display

Details:
Device: Nexus 5X
OS: 8.1.0
Dart: 2.3.0
Pushwoosh: 1.13.0

E/Pushwoosh(14343): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Firebase-PushFcmIntentService
E/Pushwoosh(14343): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/Pushwoosh(14343): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/Pushwoosh(14343): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:74)
E/Pushwoosh(14343): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:149)
E/Pushwoosh(14343): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:142)
E/Pushwoosh(14343): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.success(EventChannel.java:223)
E/Pushwoosh(14343): 	at com.pushwoosh.plugin.PushwooshPlugin$StreamHandler.sendEvent(PushwooshPlugin.java:248)
E/Pushwoosh(14343): 	at com.pushwoosh.plugin.PushwooshPlugin$StreamHandler.access$100(PushwooshPlugin.java:243)
E/Pushwoosh(14343): 	at com.pushwoosh.plugin.PushwooshPlugin.onMessageReceived(PushwooshPlugin.java:56)
E/Pushwoosh(14343): 	at com.pushwoosh.plugin.PushwooshNotificationServiceExtension.onMessageReceived(PushwooshNotificationServiceExtension.java:36)
E/Pushwoosh(14343): 	at com.pushwoosh.notification.NotificationServiceExtension.a(Unknown Source:49)
E/Pushwoosh(14343): 	at com.pushwoosh.notification.NotificationServiceExtension.handleMessage(Unknown Source:0)
E/Pushwoosh(14343): 	at com.pushwoosh.PushwooshFcmHelper.onMessageReceived(Unknown Source:74)
E/Pushwoosh(14343): 	at com.pushwoosh.PushFcmIntentService.onMessageReceived(Unknown Source:7)
E/Pushwoosh(14343): 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:402)
E/Pushwoosh(14343): 	at com.google.firebase.iid.zzg.run(Unknown Source:26)
E/Pushwoosh(14343): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/Pushwoosh(14343): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/Pushwoosh(14343): 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:7)
E/Pushwoosh(14343): 	at java.lang.Thread.run(Thread.java:764)

**Comment by wfhm** [comment]
Hi @rinlv,

Checking it.

**Comment by rinlv** [comment]
Hi @wfhm, I realize this error occur when I build with the latest Flutter. I build your example with Flutter stable ver 1.2.1, this error was disappeared and I received a notification. Thanks for your supporting.
