### ISSUE TITLE
In iOS getting 2 notification when app is in foreground

### ISSUE THREAD

**Issue by kishangohel** [Pushwoosh/pushwoosh-flutter#74]
pushwoosh_flutter: ^2.2.17

![IMG_0491](https://github.com/Pushwoosh/pushwoosh-flutter/assets/24727823/4bcb3f4e-eea6-4839-ad24-3a19c9888efe)

**Comment by enginseer-dev** [comment]
Hi @kishangohel! Are you using the Firebase plugin along with the Pushwoosh plugin in your app? Could you send the issue reproducer (sample project with our SDK integrated) to support@pushwoosh.com? Our support will thoroughly analyze it and provide you with a solution.

**Comment by enginseer-dev** [comment]
The issue was fixed with the [2.2.18](https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.18) release.
