### ISSUE TITLE
IOS Compatibility issue with FirebaseNotification

### ISSUE THREAD

**Issue by nitin123sangani** [Pushwoosh/pushwoosh-flutter#76]
issue is  firebase messaging working fine with pushwoosh in android platform.
but in ios flutter app, firebase notification receive as default notification in iOS. so, our business logic which we write on firebase onMessaageReceived is not calling.
we must require pushwoosh and firebase messaging in flutter app.(note: if we put pushwoosh integration in comment then ios side Firebase Notification Listener working fine)

**Comment by enginseer-dev** [comment]
Hi @nitin123sangani! Could you tell me what plugin version you have? A similar issue was already reported and fixed in the [2.2.16](https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.16) release.

**Comment by nitin123sangani** [comment]
we are using "pushwoosh: ^2.2.13"

**Comment by wfhm** [comment]
@nitin123sangani we had to change the package name of the plugin to “pushwoosh_flutter” after migrating the iOS logic to dynamic framework in 2.2.14. So 2.2.13 is the last release with the old “pushwoosh” package name, and it is quite outdated by now. Please try using the latest version of the new package and let us know about the results.

**Comment by nitin123sangani** [comment]
@wfhm thanks for clear this misunderstanding. now we are getting firebase notification with Pushwoosh new package. but still we are facing 2 issue.
1) 2 notification comes (i) iOS default notification (ii) our onMessageReceived when app is in foreground
2) when app is in background only received iOS default notification and when click on that default then firebase onMessageReceived call.

**Comment by enginseer-dev** [comment]
@nitin123sangani could you send us more details to better understand what's happening? Screenshots, screencasts, or a minimal project replicating the issue would be really helpful. Please email these to help@pushwoosh.com, and we'll dive into it.

**Comment by akidisdev** [comment]
@nitin123sangani The issue initially reported has been resolved with the [2.2.16](https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.16) release. We're going to close this thread now. If you need any further assistance or have new issues, feel free to reach out to our support team via email at [help@pushwoosh.com](mailto:help@pushwoosh.com).
