### ISSUE TITLE
Regarding IOS Live activities.

### ISSUE THREAD

**Issue by krishaajtak** [Pushwoosh/pushwoosh-flutter#78]
Since pushwoosh already supports live activities natively it would be great if it supported in flutter sdk. Perhaps if someone can guide. I can help in that

**Comment by enginseer-dev** [comment]
Hello, @krishaajtak 

We will need to bridge two methods from native iOS into Flutter - startLiveActivity and stopLiveActivity.
On the native side, we will create a widget for the Live Activity.

We will inform you once the task is completed.

**Comment by krishaajtak** [comment]
if you need any help in bridging, just share with me where to write. I will see how I can contribute. 

@enginseer-dev 

Regards,
Krish Bhanushali
Mobile Dev
India Today Group.

**Comment by enginseer-dev** [comment]
@krishaajtak Our code is open source.
If you'd like to contribute, please feel free to fork the repository and submit a pull request with the proposed updates.
Our team will review the suggest changes and provide feedback.

**Comment by OmerTrainer** [comment]
Any progress made regarding this issue?

**Comment by enginseer-dev** [comment]
Hello, @OmerTrainer 

The methods startLiveActivityWithToken and stopLiveActivity were added in [the latest release of the Flutter plugin - 2.2.20](https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.20).
