### ISSUE TITLE
Notification data callback if app is terminated (Android)

### ISSUE THREAD

**Issue by rajeevjaiswal** [Pushwoosh/pushwoosh-flutter#8]
Is it possible to get callback even if app is killed in Android?

**Comment by wfhm** [comment]
Hi @rajeevjaiswal,

Please let me draw your attention to the important fact that an app is not able to receive push notifications when it is killed(force stopped), therefore it is not possible to get any callback related to a push notification.

**Comment by rajeevjaiswal** [comment]
Is the behavior same for Native Android SDK implementation?

**Comment by wfhm** [comment]
@rajeevjaiswal

Yes, you are correct. This behaviour is the same for both the native framework and the cross-platform one.
