### ISSUE TITLE
No visible @interface for 'Pushwoosh' declares the selector 'startLiveActivityWithToken:completion:'

### ISSUE THREAD

**Issue by golnir** [Pushwoosh/pushwoosh-flutter#83]
there is an issue building for iOS:
ARC Semantic Issue (Xcode): No visible @interface for 'Pushwoosh' declares the selector 'startLiveActivityWithToken:completion:'
/Users/nirg/.pub-cache/hosted/pub.dev/pushwoosh_flutter-2.2.23/ios/Classes/PushwooshPlugin.m:230:36

any one solved this?

**Comment by wfhm** [comment]
@golnir Might've been introduced with the 2.2.24 release. Please let me check it and I'll get back to you shortly.

**Comment by golnir** [comment]
@wfhm 
thank you for the quick response.
we did updated to 2.2.24 and it. started, reverting to 23 didn't help even with clean & manual cache remove

**Comment by wfhm** [comment]
@golnir Just to make sure - did it start after updating from 2.2.23 to .24? Also, can you check to what versions Pushwoosh pods are resolved in the iOS project?

**Comment by golnir** [comment]
@wfhm it started with upgrading to .24
- pushwoosh_flutter (2.2.15): // is this correct?
  - pushwoosh_geozones (2.2.23):
  - pushwoosh_inbox (2.2.23):
  - PushwooshInboxUIXCFramework (6.1.2):
  - PushwooshXCFramework (6.5.14):
  - PushwooshXCFramework/Core (6.5.14)
  - PushwooshXCFramework/Geozones (6.5.14):

**Comment by wfhm** [comment]
@golnir Thanks! Found it, will be fixed shortly.

**Comment by golnir** [comment]
@wfhm great!!!
thank you very much

**Comment by wfhm** [comment]
@golnir Please try the latest version (2.2.25) and let us know about the results.

**Comment by golnir** [comment]
@wfhm working great, thank you
