### ISSUE TITLE
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by lamartinezt-indra** [Pushwoosh/pushwoosh-flutter#85]
Flutter 3.22.2
pushwoosh: ^2.2.13

Error:
`E/AndroidRuntime(27021): FATAL EXCEPTION: main
E/AndroidRuntime(27021): Process: <APP>, PID: 27021
E/AndroidRuntime(27021): java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.SecurityException: <APP>: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`

**Comment by enginseer-dev** [comment]
Hello, @lamartinezt-indra 

We've added Android 14 support in 6.6.16 version of the Android native plugin.
Which was added to Flutter plugin in the version [2.2.16](https://github.com/Pushwoosh/pushwoosh-flutter/releases/tag/2.2.16).
Please update the Flutter plugin to the latest version.

You also need to explicitly set the _android:exported_ attribute in your AndroidManifest.xml. You need to decide based on the intended use of the provider whether it should be accessible by other apps or not.
An example you can find in our [Flutter sample app](https://github.com/Pushwoosh/pushwoosh-flutter-sample/blob/main/demoapp/android/app/src/main/AndroidManifest.xml).

**Comment by wfhm** [comment]
@lamartinezt-indra just in case you missed the update - we had to change the package name from `pushwoosh` to `pushwoosh_flutter` starting with the 2.2.14 release. Therefore, the dependency should be imported as below:

pushwoosh_flutter: ^2.2.25
