### ISSUE TITLE
[Bug]: iOS, Foreground Notification is send twice

### ISSUE THREAD

**Issue by aliakkawi** [Pushwoosh/pushwoosh-flutter#91]
### Documentation

- [X] I've checked the guide, but it doesn't help me to resolve the issue.

### Description

Hi, we are using FCM along with the Pushwoosh SDK. Before integrating Pushwwosh we used to handle Foreground Alerts using Local Notifications and therefore after implementing Pushwwosh the Notification is sent twice for iOS.
We've already tried the following solutions:
1.
`Pushwoosh.getInstance.setShowForegroundAlert(false);
2. In the AppDelegate:
```
override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void)
    {
        if UIApplication.shared.applicationState == .active {
            completionHandler([])
        } else {
            completionHandler([.alert, .badge, .sound])
        }
    }
```

### Bug severity

High

### Steps to Reproduce

Send FCM Notifications for iOS devices.

### Your Pushwoosh Flutter plugin version

2.2.25

### flutter package version

3.24.3

### Affected platforms

- [ ] Android
- [X] iOS

### Affected OS versions and/or devices

iOS devices

**Comment by enginseer-dev** [comment]
Hello, @aliakkawi 

The double notification bug was related to the bug in the release of iOS 18: https://forums.developer.apple.com/forums/thread/762126

We’ve addressed this in the latest releases of the Flutter plugin.

Thank you for your feedback and for bringing this to our attention!
